// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gcms/internal/conf"
	"gcms/internal/data"
	"gcms/internal/migration"
	"github.com/google/wire"
)

// Injectors from wire.go:

func wireApp(data2 *conf.Data) (*migration.Migration, func(), error) {
	db, cleanup, err := data.NewDb(data2)
	if err != nil {
		return nil, nil, err
	}
	migrationMigration := migration.NewMigration(db)
	return migrationMigration, func() {
		cleanup()
	}, nil
}

// wire.go:

var migrationSet = wire.NewSet(migration.NewMigration)

var databaseSet = wire.NewSet(data.NewDb)
