// Code generated by protoc-gen-gin. DO NOT EDIT.
package code

func init() {
	ErrMap = map[int]*RespError{
		ErrParameterInvalid: {Code: ErrParameterInvalid, Message: "参数校验失败: %s"},
		ErrUserNotFound:     {Code: ErrUserNotFound, Message: "用户未找到: %s"},
		ErrUserAuthFaild:    {Code: ErrUserAuthFaild, Message: "用户认证失败"},
		ErrUserExist:        {Code: ErrUserExist, Message: "用户已存在: %s"},
	}
}
