// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gcms/internal/conf"
	"gcms/internal/data"
	"gcms/internal/domain"
	"gcms/internal/handler"
	"gcms/internal/middleware"
	"gcms/internal/server"
	"gcms/internal/service"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func wireApp(confData *conf.Data, confJwt *conf.JWT) (*gin.Engine, func(), error) {
	jwt := middleware.NewJwt(confJwt)
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userDomainService := domain.NewUserDomainService(userRepo)
	userService := service.NewUserService(userDomainService)
	userHandler := handler.NewUserHandler(userService)
	engine := server.NewHTTPServer(jwt, userHandler)
	return engine, func() {
		cleanup()
	}, nil
}

// wire.go:

var domainSet = wire.NewSet(domain.NewUserDomainService)

var dataSet = wire.NewSet(data.NewData, data.NewUserRepo)

var serviceSet = wire.NewSet(service.NewUserService)

var handlerSet = wire.NewSet(handler.NewUserHandler)

var serverSet = wire.NewSet(server.NewHTTPServer)

var jwtSet = wire.NewSet(middleware.NewJwt)
